services:
  base-alpine:
    image: ghcr.io/cybernop/build-fhir-ig:base-alpine
    build:
      dockerfile: Dockerfile.base-alpine

  base-ubuntu:
    image: ghcr.io/cybernop/build-fhir-ig:base-ubuntu
    build:
      dockerfile: Dockerfile.base-ubuntu

  online-alpine:
    image: cybernop/build-fhir-ig:online-alpine
    build:
      dockerfile: Dockerfile.final-alpine
      target: online

  online-ubuntu:
    image: cybernop/build-fhir-ig:online-ubuntu
    build:
      dockerfile: Dockerfile.final-ubuntu
      target: online

  offline-alpine:
    image: cybernop/build-fhir-ig:1.8.16-alpine
    build:
      dockerfile: Dockerfile.final-alpine
      target: offline
      args:
        - PUB_VERSION=1.8.16

  offline-ubuntu:
    image: cybernop/build-fhir-ig:1.8.16-ubuntu
    build:
      dockerfile: Dockerfile.final-ubuntu
      target: offline
      args:
        - PUB_VERSION=1.8.16

  offline-sushi-alpine:
    image: cybernop/build-fhir-ig:1.8.16-sushi-3.14.0-alpine
    build:
      dockerfile: Dockerfile.final-alpine
      target: offline-sushi
      args:
        - PUB_VERSION=1.8.16
        - SUSHI_VERSION=3.14.0

  offline-sushi-ubuntu:
    image: cybernop/build-fhir-ig:1.8.16-sushi-3.14.0-ubuntu
    build:
      dockerfile: Dockerfile.final-ubuntu
      target: offline-sushi
      args:
        - PUB_VERSION=1.8.16
        - SUSHI_VERSION=3.14.0

  flex-alpine:
    image: cybernop/build-fhir-ig:flex-alpine
    build:
      dockerfile: Dockerfile.flex-alpine
      target: flex

  flex-ubuntu:
    image: cybernop/build-fhir-ig:flex-ubuntu
    build:
      dockerfile: Dockerfile.flex-ubuntu
      target: flex

  flex-npm-alpine:
    image: cybernop/build-fhir-ig:flex-npm-alpine
    build:
      dockerfile: Dockerfile.flex-alpine
      target: flex-npm

  flex-npm-ubuntu:
    image: cybernop/build-fhir-ig:flex-npm-ubuntu
    build:
      dockerfile: Dockerfile.flex-ubuntu
      target: flex-npm
