services:
  build-fhir-ig-base-ubuntu:
    image: ghcr.io/cybernop/build-fhir-ig:base-ubuntu
    build:
      dockerfile: Dockerfile.base-ubuntu

  build-fhir-ig-base-alpine:
    image: ghcr.io/cybernop/build-fhir-ig:base-alpine
    build:
      dockerfile: Dockerfile.base-alpine

  build-fhir-ig-node-base-ubuntu:
    image: ghcr.io/cybernop/build-fhir-ig:base-nodejs-ubuntu
    build:
      dockerfile: Dockerfile.base-nodejs-ubuntu

  build-fhir-ig-node-base-alpine:
    image: ghcr.io/cybernop/build-fhir-ig:base-nodejs-alpine
    build:
      dockerfile: Dockerfile.base-nodejs-alpine

  build-fhir-ig-online:
    image: cybernop/build-fhir-ig:online
    build:
      dockerfile: Dockerfile.final
      target: online
      args:
        - OS_BASE=ubuntu

  build-fhir-ig-1-8-8-online:
    image: cybernop/build-fhir-ig:online-1.8.16
    build:
      dockerfile: Dockerfile.final
      target: online
      args:
        - OS_BASE=ubuntu
        - PUB_VERSION=1.8.16

  build-fhir-ig-offline:
    image: cybernop/build-fhir-ig:latest
    build:
      dockerfile: Dockerfile.final
      target: offline
      args:
        - OS_BASE=ubuntu

  build-fhir-ig-1-8-8-offline:
    image: cybernop/build-fhir-ig:1.8.16
    build:
      dockerfile: Dockerfile.final
      target: offline
      args:
        - OS_BASE=ubuntu
        - PUB_VERSION=1.8.16

  build-fhir-ig-1-8-8-sushi-offline:
    image: cybernop/build-fhir-ig:1.8.16-sushi
    build:
      dockerfile: Dockerfile.final
      target: offline-sushi
      args:
        - OS_BASE=ubuntu
        - PUB_VERSION=1.8.16
        - SUSHI_VERSION=3.14.0
