services:
  build-fhir-ig-base:
    image: ghcr.io/cybernop/build-fhir-ig:base-ubuntu
    build:
      dockerfile: Dockerfile.base-ubuntu

  build-fhir-ig-node-base:
    image: ghcr.io/cybernop/build-fhir-ig:base-nodejs-ubuntu
    build:
      dockerfile: Dockerfile.base-nodejs-ubuntu

  build-fhir-ig-online:
    image: ghcr.io/cybernop/build-fhir-ig:online
    build:
      dockerfile: Dockerfile.final
      target: online
      args:
        - OS_BASE=ubuntu

  build-fhir-ig-1-8-8-online:
    image: ghcr.io/cybernop/build-fhir-ig:online-1.8.8
    build:
      dockerfile: Dockerfile.final
      target: online
      args:
        - OS_BASE=ubuntu
        - PUB_VERSION=1.8.8

  build-fhir-ig-offline:
    image: ghcr.io/cybernop/build-fhir-ig:latest
    build:
      dockerfile: Dockerfile.final
      target: offline
      args:
        - OS_BASE=ubuntu

  build-fhir-ig-1-8-8-offline:
    image: ghcr.io/cybernop/build-fhir-ig:1.8.8
    build:
      dockerfile: Dockerfile.final
      target: offline
      args:
        - OS_BASE=ubuntu
        - PUB_VERSION=1.8.8
