services:
  build-fhir-ig-base:
    image: ghcr.io/cybernop/build-fhir-ig:base-ubuntu
    build:
      target: base-ubuntu

  build-fhir-ig-online:
    image: ghcr.io/cybernop/build-fhir-ig:online-ubuntu
    build:
      target: online
      args:
        - OS_BASE=ubuntu

  build-fhir-ig-offline:
    image: ghcr.io/cybernop/build-fhir-ig:offline-ubuntu
    build:
      target: offline
      args:
        - OS_BASE=ubuntu
