FROM ghcr.io/cybernop/build-fhir-ig:base-ubuntu

# Install tools and libs for specific Node version and NPM
RUN apt update \
    && apt install -y \
    libicu74

# Get and install Node install script
RUN wget https://deb.nodesource.com/setup_20.x -O nodesource_setup.sh \
    && bash ./nodesource_setup.sh \
    && rm nodesource_setup.sh

# Install NodeJS (and NPM)
RUN apt update \
    && apt install -y \
    nodejs
