name: Docker Images

on:
  push:
    paths:
      - ".github/workflows/docker-images.yml"
      - "**/Dockerfile.base-ubuntu"
      - "**/Dockerfile.base-nodejs-ubuntu"
      - "**/Dockerfile.final"
      - "**/entrypoint*.sh"
      - "**/genonce.sh"
  workflow_dispatch:

env:
  CACHE_REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  LATEST_PUB_VERSION: "1.8.13"
  DEFAULT_OS: "ubuntu"
  DEFAULT_VERSION: "offline"
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  base-images:
    name: Base images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu"
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Log into github Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      # Build and push Docker image with Buildx (push on tag)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: docker
          file: "docker/Dockerfile.base-${{ matrix.os }}"
          platforms: ${{ env.PLATFORMS }}
          push: true
          cache-from: type=registry,ref=${{ env.CACHE_REGISTRY }}/${{ env.IMAGE_NAME }}:base-${{ matrix.os }}-buildcache
          cache-to: type=registry,ref=${{ env.CACHE_REGISTRY }}/${{ env.IMAGE_NAME }}:base-${{ matrix.os }}-buildcache,mode=max
          tags: ${{ env.CACHE_REGISTRY }}/${{ env.IMAGE_NAME }}:base-${{ matrix.os }}

  base-njs-images:
    name: NodeJS base images
    runs-on: ubuntu-latest
    needs:
        - base-images
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu"
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Log into github Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      # Build and push Docker image with Buildx (push on tag)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: docker
          file: "docker/Dockerfile.base-nodejs-${{ matrix.os }}"
          platforms: ${{ env.PLATFORMS }}
          push: true
          cache-from: type=registry,ref=${{ env.CACHE_REGISTRY }}/${{ env.IMAGE_NAME }}:base-nodejs-${{ matrix.os }}-buildcache
          cache-to: type=registry,ref=${{ env.CACHE_REGISTRY }}/${{ env.IMAGE_NAME }}:base-nodejs-${{ matrix.os }}-buildcache,mode=max
          tags: ${{ env.CACHE_REGISTRY }}/${{ env.IMAGE_NAME }}:base-nodejs-${{ matrix.os }}

  without-sushi:
    name: Images w/o Sushi
    runs-on: ubuntu-latest
    needs:
        - base-images
    strategy:
      fail-fast: false
      matrix:
        pub_version:
          - "online"
          - "1.8.8"
          - "1.8.9"
          - "1.8.10"
          - "1.8.11"
          - "1.8.12"
          - "1.8.13"
        os:
          - "ubuntu"
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log into github Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CACHE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.pub_version }},enable=${{ matrix.os == env.DEFAULT_OS }}
            type=raw,value=${{ matrix.pub_version }}-${{ matrix.os }},enable=${{ matrix.os != env.DEFAULT_OS }}
            type=raw,value=latest,enable=${{ matrix.os == env.DEFAULT_OS }},enable=${{ matrix.os == env.DEFAULT_OS && matrix.pub_version == env.LATEST_PUB_VERSION }}
            type=raw,value=latest-${{ matrix.os }},enable=${{ matrix.os != env.DEFAULT_OS && matrix.pub_version == env.LATEST_PUB_VERSION }}

      # Build and push Docker image with Buildx (push on tag)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: docker
          file: "docker/Dockerfile.final"
          platforms: ${{ env.PLATFORMS }}
          push: true
          cache-from: type=registry,ref=${{ env.CACHE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.pub_version }}-${{ matrix.os }}-buildcache
          cache-to: type=registry,ref=${{ env.CACHE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.pub_version }}-${{ matrix.os }}-buildcache,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: ${{ matrix.pub_version == 'online' && 'online' || 'offline' }}
          build-args: |
            OS_BASE=${{ matrix.os }}
            PUB_VERSION=${{ matrix.pub_version }}

  image-with-sushi:
    name: Images w/ Sushi
    runs-on: ubuntu-latest
    needs:
        - base-njs-images
    strategy:
      fail-fast: false
      matrix:
        pub_version:
          - "online"
          - "1.8.8"
          - "1.8.9"
          - "1.8.10"
          - "1.8.11"
          - "1.8.12"
          - "1.8.13"
        os:
          - "ubuntu"
        sushi_version:
          - "3.10.0"
          - "3.11.0"
          - "3.11.1"
          - "3.12.0"
          - "3.12.1"
          - "3.13.0"
          - "3.13.1"
          - "3.14.0"
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log into github Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.pub_version }}-sushi-${{ matrix.sushi_version }},enable=${{ matrix.os == env.DEFAULT_OS }}
            type=raw,value=${{ matrix.pub_version }}-sushi-${{ matrix.sushi_version }}-${{ matrix.os }},enable=${{ matrix.os != env.DEFAULT_OS }}
            type=raw,value=latest-sushi-${{ matrix.sushi_version }},enable=${{ matrix.os == env.DEFAULT_OS }},enable=${{ matrix.os == env.DEFAULT_OS && matrix.pub_version == env.LATEST_PUB_VERSION }}
            type=raw,value=latest-sushi-${{ matrix.sushi_version }}-${{ matrix.os }},enable=${{ matrix.os != env.DEFAULT_OS && matrix.pub_version == env.LATEST_PUB_VERSION }}

      # Build and push Docker image with Buildx (push on tag)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: docker
          file: "docker/Dockerfile.final"
          platforms: ${{ env.PLATFORMS }}
          push: true
          cache-from: type=registry,ref=${{ env.CACHE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.pub_version }}-sushi-${{ matrix.sushi_version }}-${{ matrix.os }}-buildcache
          cache-to: type=registry,ref=${{ env.CACHE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.pub_version }}-sushi-${{ matrix.sushi_version }}-${{ matrix.os }}-buildcache,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: ${{ matrix.pub_version == 'online' && 'online' || 'offline' }}-sushi
          build-args: |
            OS_BASE=${{ matrix.os }}
            PUB_VERSION=${{ matrix.pub_version }}
            SUSHI_VERSION=${{ matrix.sushi_version }}
